/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for stl HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    test
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloJNI_test__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     HelloJNI
 * Method:    test
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HelloJNI_test__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     HelloJNI
 * Method:    ctime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNI_ctime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
